# -*- coding: utf-8 -*-
"""fusion_demo

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1TCin3aM_pDcSYNtFs2Z2GOKBCf3rs1KK
"""

import torch
import torch.nn as nn
import torch.nn.functional as F

class FusionDemo(nn.Module):
    """
    Minimal Adaptive Fusion Layer.
    alpha = sigmoid(MLP([h_t, h_g, mat_emb, hor_emb]))
    fused = alpha*h_t + (1-alpha)*h_g
    """

    def __init__(self, hidden_dim=32, num_mats=8, num_horizons=4, embed_dim=8):
        super().__init__()
        self.mat_emb = nn.Embedding(num_mats, embed_dim)
        self.hor_emb = nn.Embedding(num_horizons, embed_dim)

        self.alpha_mlp = nn.Sequential(
            nn.Linear(hidden_dim*2 + embed_dim*2, hidden_dim),
            nn.ReLU(),
            nn.Linear(hidden_dim, 1)
        )

    def forward(self, h_t, h_g, mat_id, hor_id):
        m = self.mat_emb(mat_id)  # [B, E]
        h = self.hor_emb(hor_id)  # [B, E]

        fusion_input = torch.cat([h_t, h_g, m, h], dim=-1)
        alpha = torch.sigmoid(self.alpha_mlp(fusion_input))  # [B,1]

        fused = alpha*h_t + (1-alpha)*h_g  # [B,H]
        return fused, alpha