# -*- coding: utf-8 -*-
"""gat_demo

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1TCin3aM_pDcSYNtFs2Z2GOKBCf3rs1KK
"""

import torch
import torch.nn as nn
import torch.nn.functional as F

class GATDemo(nn.Module):
    """
    Minimal GAT Branch for Demo.
    No torch_geometric. Uses:
      - simple node embedding
      - fake attention based on dot products
    """

    def __init__(self, hidden_dim=32, num_nodes=5, node_feat_dim=4):
        super().__init__()
        self.node_proj = nn.Linear(node_feat_dim, hidden_dim)
        self.attn_score = nn.Linear(hidden_dim, 1)

    def forward(self, x):
        """
        x: [N, F] dummy node features
        returns: structural embedding for node 0
        """
        h = self.node_proj(x)  # [N, H]

        # fake attention = softmax(dot-score)
        scores = F.softmax(self.attn_score(h), dim=0)  # [N, 1]

        # structural embedding = weighted sum
        structural_emb = torch.sum(h * scores, dim=0)  # [H]

        # expand to [B, H]
        return structural_emb.unsqueeze(0)