# -*- coding: utf-8 -*-
"""risk_demo

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1TCin3aM_pDcSYNtFs2Z2GOKBCf3rs1KK
"""

import torch
import torch.nn as nn

class RiskDemo(nn.Module):
    """
    Minimal Risk Scoring Layer for Demo.
    Computes:
      - Budget Risk
      - Stockout (Lead-time) Risk
      - Structural Dependency Risk (based on GAT attention)
    """

    def __init__(self):
        super().__init__()

    def forward(self, forecast, price, stock, lead_time, attn):
        """
        forecast: [B]
        price: [B]
        stock: [B]
        lead_time: [B]
        attn: [B] or scalar (dependency proxy)

        returns dict
        """
        cost = forecast * price
        budget_risk = cost / 2000.0            # small budget
        stock_risk = (forecast * (lead_time/30)) / (stock + 1e-6)
        dependency_risk = attn                  # directly pass GAT attention score

        return {
            "budget_risk": budget_risk.item(),
            "stock_risk": stock_risk.item(),
            "dependency_risk": dependency_risk.item(),
        }