# -*- coding: utf-8 -*-
"""tft_demo

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1TCin3aM_pDcSYNtFs2Z2GOKBCf3rs1KK
"""

import torch
import torch.nn as nn
import torch.nn.functional as F

class TFTDemo(nn.Module):
    """
    Minimal Temporal Branch for Demo.
    Replaces full TFT with:
      - simple linear embedding
      - single GRU layer
      - single-head attention
    Output: temporal embedding [B, H]
    """

    def __init__(self, hidden_dim=32, input_dim=4):
        super().__init__()
        self.hidden_dim = hidden_dim

        self.input_proj = nn.Linear(input_dim, hidden_dim)
        self.gru = nn.GRU(hidden_dim, hidden_dim, batch_first=True)
        self.attn = nn.Linear(hidden_dim, 1)

    def forward(self, x):
        """
        x: [B, T, F] dummy time-series
        """
        x = self.input_proj(x)          # [B, T, H]
        out, _ = self.gru(x)            # [B, T, H]

        # attention over time
        weights = F.softmax(self.attn(out), dim=1)  # [B, T, 1]
        temporal_emb = torch.sum(out * weights, dim=1)  # [B, H]

        return temporal_emb